SET 'execution.checkpointing.interval' = '1min';
SET pipeline.name=3c36bc68_edr_batch04;
SET yarn.application.queue=root;
DROP TABLE IF EXISTS EdrTable;
CREATE Temporary TABLE EdrTable (
		`uuid`  varchar,
		`service` row(`name` varchar),
        `source_data` string,
		`organization` row(`id` varchar),
        `agent` row(`type` varchar),
        `error` row(`code` varchar,
                    `message` varchar),
        `log` row(`level` varchar,
                  `type` varchar),
        `sysmon` row(`dns` row(`status_code` varchar),
                     `file` row(`archived` varchar,
                                `is_executable` varchar)),
        `related` row(`hash` array<varchar>,
                      `hosts` array<varchar>,
                      `ip` array<varchar>,
                      `user` array<varchar>),
		`observer` row(`product`  varchar,
                `ip` varchar,
                `name` varchar,
				`vendor`  varchar,
				`type` varchar),
		`event` row(`created` varchar,
                    `channel` varchar,
                    `category` array<varchar>,
                    `code` int,
                    `host` varchar,
                    `ingested` varchar,
                    `message` varchar,
                    `dataset`  varchar,
                    `original` string,
                    `module` varchar,
                    `provider` varchar,
                    `kind` varchar,
                    `outcome` varchar,
                    `type` array<varchar>,
                    `action` varchar,
                    `id` varchar,
                    `severity` varchar,
                    `reason` varchar),
		`rule` row(`name` varchar),
		`sensor` row(`id` varchar),
		`host` row(`name` varchar,
                   `mac` varchar,
                   `os` row(`name` varchar,
                            `platform` varchar,
                            `version` varchar),
                   `architecture` varchar),
		`network` row(`community_id` varchar,
		              `transport` varchar,
                      `type` varchar,
                      `protocol` varchar,
				      `direction` varchar),
		`process` row(`name` varchar,
		            `args` varchar,
                    `args_count` varchar,
                    `working_directory` varchar,
                    `title` varchar,
                    `executable` varchar,
                    `command_line` varchar,
			        `pid` varchar,
				`thread` row(`id` varchar),
                                `entity_id` varchar,
                                `hash` row(`sha1` varchar,
				                           `imphash` varchar,
                                        `sha256` varchar,
	                                      `md5` varchar),
				`parent` row(`executable` varchar,
				                `args` varchar,
						        `pid` varchar,
					         `name` varchar,
						     `command_line` varchar,
						     `entity_id` varchar),
				 `pe` row( `company` varchar,
		                              `sha256` varchar,
									 `description` varchar,
									 `file_version` varchar,
									 `imphash` varchar,
									 `original_file_name` varchar,
									 `product` varchar)
									),
		`source` row(`ip` varchar,
					`port` int,
                    `address` varchar,
					`locality` varchar,
					`domain` varchar,
					`user` row(`name` varchar, `domain` varchar),
					`as` row(`organization` row(`name` varchar),
						`number` varchar,
						`locality` varchar),
					`geo` row(`city_name` varchar,
						`country_code` varchar,
						`country_name` varchar,
						`region_name` varchar ,
						`continent_code` varchar,
						`location` row(`lat` double,`lon` double),
						`address` varchar,
						`domain` varchar,
						`ip` varchar,
						`port` int)),
		`destination` row(`ip` varchar,
					`port` int,
					`locality` varchar,
					`domain` varchar,
					`as` row(`organization` row(`name` varchar),
						`number` varchar,
						`locality` varchar),
					`geo` row(`city_name` varchar,
						`country_code` varchar,
						`country_name` varchar,
						`region_name` varchar ,
						`continent_code` varchar,
						`location` row(`lat` double,`lon` double),
						`address` varchar,
						`domain` varchar,
						`ip` varchar,
						`port` int)),
		`user` row(`name` varchar,
					`domain` varchar,
					`id`    varchar,
					`type`  varchar),
		`threatintel` row(`entity` varchar,
					`days` int,
                    `event_data` varchar,
                    `malware` row(`malware` varchar,
                                  `timestamp` timestamp),
					`severity` varchar,
                    `tags` varchar,
                    `white_list` varchar,
					`lookup` varchar),
		`registry` row(`path` varchar,
                    `hive` varchar,
                    `key` varchar,
                    `data` row(`strings` varchar,
                               `type` varchar),
					`value`  varchar),
		`hash` row(`imphash` varchar,
		            `sha256` varchar,
					`sha1` varchar,
					`md5`  varchar),
		`dns` row(`answers` array<varchar>,
                  `resolved_ip` array<varchar>,
                  `question` row(`domain` varchar,
					             `name`  varchar)),
		`file` row(`name` varchar,
				`path`  varchar,
                `size` int,
                `directory` varchar,
                `extension` varchar,
				`code_signature` row(`signed` varchar,
				                        `subject_name` varchar,
                                        `valid` varchar,
				                        `status` varchar),
				`pe` row(`imphash` varchar,
				            `description` varchar,
					    `product` varchar,
					    `company` varchar,
					    `file_version` varchar,
						`original_file_name` varchar),
				`hash` row( `md5` varchar,
				               `imphash` varchar,
						`sha1` varchar,
						`sha256` varchar)),
                `winlog`  row (`activity_id` varchar,
                                `channel` varchar,
                                `computer_name` varchar,
                                `event_id` int,
                                `name` varchar,
                                `logon` row(`failure` row(`status` varchar,
                                                        `sub_status` varchar),
                                        `id` varchar,
                                        `type` varchar),
                                `opcode` varchar,
                                `process` row(`pid` varchar,
                                        `thread` row(`id` varchar)),
                                `provider_guid` varchar,
                                `provider_name` varchar,
                                `record_id` varchar,
                                `task` varchar,
                                `user` row(`domain` varchar,
                                        `identifier` varchar,
                                        `name` varchar,
                                        `type` varchar),
                                `version` varchar,
                                `event_data` row(`channel` varchar,
                                                `accesses` varchar,
                                                `accessgranted` varchar,
                                                `accesslist` varchar,
                                                `accessmask` varchar,
                                                `accessmaskdescription` varchar,
                                                `accessreason` varchar,
                                                `accessremoved` varchar,
                                                `accesslistdescription` varchar,
                                                `accountexpires` varchar,
                                                `action` varchar,
                                                `action_id` varchar,
                                                `action_name` varchar,
                                                `additional_actions_id` varchar,
                                                `additional_actions_` varchar,
                                                `additionalinfo` varchar,
                                                `additionalinfo2` varchar,
                                                `address` varchar,
                                                `allowedtodelegateto` varchar,
                                                `appcorrelationid` varchar,
                                                `appid` varchar,
                                                `appname` varchar,
                                                `application` varchar,
                                                `applicationpath` varchar,
                                                `assemblypath` varchar,
                                                `attributeldapdisplayname` varchar,
                                                `attributesyntaxoid` varchar,
                                                `attributevalue` varchar,
                                                `auditpolicychanges` varchar,
                                                `auditsourcename` varchar,
                                                `auditpolicychangesdescription` varchar,
                                                `authenticationalgorithm` varchar,
                                                `authenticationpackagename` varchar,
                                                `binary` varchar,
                                                `bssid` varchar,
                                                `bsstype` varchar,
                                                `callerprocessid` varchar,
                                                `callerprocessname` varchar,
                                                `callingprocessname` varchar,
                                                `callstack` varchar,
                                                `calltrace` varchar,
                                                `caption` varchar,
                                                `category_id` varchar,
                                                `category_name` varchar,
                                                `categoryid` varchar,
                                                `certissuername` varchar,
                                                `certserialnumber` varchar,
                                                `certthumbprint` varchar,
                                                `cipheralgorithm` varchar,
                                                `classid` varchar,
                                                `classname` varchar,
                                                `clientinfo` varchar,
                                                `clientprocessid` varchar,
                                                `clientprocessstartkey` varchar,
                                                `commandline` varchar,
                                                `company` varchar,
                                                `computeraccountchange` varchar,
                                                `configuration` varchar,
                                                `configurationfilehash` varchar,
                                                `connectionid` varchar,
                                                `connectionmode` varchar,
                                                `consumer` varchar,
                                                `contents` varchar,
                                                `contextinfo` varchar,
                                                `crashonauditfailvalue` varchar,
                                                `creationutctime` varchar,
                                                `ddtype` varchar,
                                                `description` varchar,
                                                `details` varchar,
                                                `detection_id` varchar,
                                                `detection_time` varchar,
                                                `detection_user` varchar,
                                                `devicedescription` varchar,
                                                `devicename` varchar,
                                                `direction` varchar,
                                                `directiondescription` varchar,
                                                `displayname` varchar,
                                                `dnshostname` varchar,
                                                `domainbehaviorversion` varchar,
                                                `domainname` varchar,
                                                `domainpolicychanged` varchar,
                                                `domainsid` varchar,
                                                `drivename` varchar,
                                                `dsname` varchar,
                                                `dummy` varchar,
                                                `elevatedtoken` varchar,
                                                `engine_version` varchar,
                                                `engineversion` varchar,
                                                `error_code` varchar,
                                                `error_description` varchar,
                                                `errorcode` varchar,
                                                `event` row(`destinationisipv6` varchar),
                                                `eventnamespace` varchar,
                                                `eventsourceid` varchar,
                                                `eventtype` varchar,
                                                `exceptioncode` varchar,
                                                `execution_id` varchar,
                                                `execution_name` varchar,
                                                `failurecode` varchar,
                                                `failurereason` varchar,
                                                `failurereasondescription` varchar,
                                                `feature` varchar,
                                                `feature_name` varchar,
                                                `filehash` varchar,
                                                `filename` varchar,
                                                `filenamebuffer` varchar,
                                                `fileversion` varchar,
                                                `filter` varchar,
                                                `filterorigin` varchar,
                                                `filterrtid` varchar,
                                                `forcelogoff` varchar,
                                                `fqdn` varchar,
                                                `fwlink` varchar,
                                                `grantedaccess` varchar,
                                                `grouptypechange` varchar,
                                                `handleid` varchar,
                                                `hash` varchar,
                                                `hashes` varchar,
                                                `headerflags` varchar,
                                                `hivename` varchar,
                                                `homedirectory` varchar,
                                                `homepath` varchar,
                                                `hostversion` varchar,
                                                `imagename` varchar,
                                                `imagepath` varchar,
                                                `impersonationlevel` varchar,
                                                `initiated` varchar,
                                                `integritylevel` varchar,
                                                `interfacedescription` varchar,
                                                `interfaceguid` varchar,
                                                `keylength` varchar,
                                                `keywords` varchar,
                                                `layername` varchar,
                                                `layerrtid` varchar,
                                                `layernamedescription` varchar,
                                                `ldapdisplayname` varchar,
                                                `level` varchar,
                                                `lmpackagename` varchar,
                                                `localname` varchar,
                                                `lockoutduration` varchar,
                                                `lockoutobservationwindow` varchar,
                                                `lockoutthreshold` varchar,
                                                `logonguid` varchar,
                                                `logonhours` varchar,
                                                `logonid` varchar,
                                                `logon` row(`id` varchar),
                                                `logonprocessname` varchar,
                                                `logontype` varchar,
                                                `machineaccountquota` varchar,
                                                `mandatorylabel` varchar,
                                                `masterkeyid` varchar,
                                                `maxpasswordage` varchar,
                                                `membername` varchar,
                                                `membersid` varchar,
                                                `message` varchar,
                                                `minpasswordage` varchar,
                                                `minpasswordlength` varchar,
                                                `mixeddomainmode` varchar,
                                                `modifyingapplication` varchar,
                                                `name` varchar,
                                                `new_value` varchar,
                                                `newname` varchar,
                                                `newsd` varchar,
                                                `newtargetusername` varchar,
                                                `newtemplatecontent` varchar,
                                                `newthreadid` varchar,
                                                `newtime` varchar,
                                                `newuacvalue` varchar,
                                                `newvalue` varchar,
                                                `newvaluetype` varchar,
                                                `objectclass` varchar,
                                                `objectdn` varchar,
                                                `objectguid` varchar,
                                                `objectname` varchar,
                                                `objectserver` varchar,
                                                `objecttype` varchar,
                                                `objectvaluename` varchar,
                                                `oeminformation` varchar,
                                                `old_value` varchar,
                                                `oldsd` varchar,
                                                `oldtargetusername` varchar,
                                                `olduacvalue` varchar,
                                                `oldvalue` varchar,
                                                `oldvaluetype` varchar,
                                                `onexenabled` varchar,
                                                `opcorrelationid` varchar,
                                                `operation` varchar,
                                                `operationtype` varchar,
                                                `origin` varchar,
                                                `origin_id` varchar,
                                                `origin_name` varchar,
                                                `originalfilename` varchar,
                                                `outcome` varchar,
                                                `packagefullname` varchar,
                                                `packagename` varchar,
                                                `packagepath` varchar,
                                                `param1` varchar,
                                                `param2` varchar,
                                                `param3` varchar,
                                                `parentuser` varchar,
                                                `parentcommandline` varchar,
                                                `parentimage` varchar,
                                                `parentprocessid` varchar,
                                                `passwordhistorylength` varchar,
                                                `passwordlastset` varchar,
                                                `passwordproperties` varchar,
                                                `path` varchar,
                                                `payload` varchar,
                                                `phytype` varchar,
                                                `pipename` varchar,
                                                `policyname` varchar,
                                                `possiblecause` varchar,
                                                `post_clean_status` varchar,
                                                `pre_execution_status` varchar,
                                                `preauthtype` varchar,
                                                `previouscreationutctime` varchar,
                                                `previoustime` varchar,
                                                `primarygroupid` varchar,
                                                `privilegelist` varchar,
                                                `process_name` varchar,
                                                `processcommandline` varchar,
                                                `processname` varchar,
                                                `processnamebuffer` varchar,
                                                `processpath` varchar,
                                                `processid` varchar,
                                                `product` varchar,
                                                `product_name` varchar,
                                                `product_version` varchar,
                                                `profilename` varchar,
                                                `profilepath` varchar,
                                                `properties` varchar,
                                                `protocol` varchar,
                                                `provider` varchar,
                                                `providername` varchar,
                                                `provider_name` varchar,
                                                `puacount` varchar,
                                                `puapolicyid` varchar,
                                                `query` varchar,
                                                `queryname` varchar,
                                                `qname` varchar,
                                                `queryresults` varchar,
                                                `reason` varchar,
                                                `recoverykeyid` varchar,
                                                `recoveryserver` varchar,
                                                `relativetargetname` varchar,
                                                `remediation_user` varchar,
                                                `remotemachineid` varchar,
                                                `remotename` varchar,
                                                `remoteuserid` varchar,
                                                `requestedpolicy` varchar,
                                                `resourceattributes` varchar,
                                                `restrictedadminmode` varchar,
                                                `restrictedsidcount` varchar,
                                                `rpccallclientlocality` varchar,
                                                `ruleid` varchar,
                                                `rulename` varchar,
                                                `samaccountname` varchar,
                                                `sampledata` varchar,
                                                `samplelength` varchar,
                                                `schemaversion` varchar,
                                                `scriptpath` varchar,
                                                `scriptblockid` varchar,
                                                `scriptblocktext` varchar,
                                                `searchfilter` varchar,
                                                `security_intelligence_version` varchar,
                                                `securityid` varchar,
                                                `servername` varchar,
                                                `service` varchar,
                                                `serviceaccount` varchar,
                                                `servicefilename` varchar,
                                                `servicename` varchar,
                                                `serviceprincipalnames` varchar,
                                                `servicesid` varchar,
                                                `servicestarttype` varchar,
                                                `servicetype` varchar,
                                                `session` varchar,
                                                `sessionid` varchar,
                                                `sessionname` varchar,
                                                `severity` varchar,
                                                `severity_id` varchar,
                                                `severity_name` varchar,
                                                `sharelocalpath` varchar,
                                                `sharename` varchar,
                                                `sidhistory` varchar,
                                                `sidlist` varchar,
                                                `signed` varchar,
                                                `signature` varchar,
                                                `signaturestatus` varchar,
                                                `source` varchar,
                                                `sourceparentimage` varchar,
                                                `sourceaddress` varchar,
                                                `source_id` varchar,
                                                `source_name` varchar,
                                                `sourcename` varchar,
                                                `sourcecommandline` varchar,
                                                `sourcefile` varchar,
                                                `sourcefilename` varchar,
                                                `sourcehostname` varchar,
                                                `sourceimage` varchar,
                                                `sourceip` varchar,
                                                `sourceline` varchar,
                                                `sourceport` varchar,
                                                `sourceportname` varchar,
                                                `sourcetag` varchar,
                                                `sourceuser` varchar,
                                                `ssid` varchar,
                                                `startaddress` varchar,
                                                `startfunction` varchar,
                                                `startmodule` varchar,
                                                `starttype` varchar,
                                                `state` varchar,
                                                `status` varchar,
                                                `status_code` varchar,
                                                `statusdescription` varchar,
                                                `status_description` varchar,
                                                `subcategoryguid` varchar,
                                                `subcategoryid` varchar,
                                                `subjectdomainname` varchar,
                                                `subjectlogonid` varchar,
                                                `subjectname` varchar,
                                                `subjectusername` varchar,
                                                `subjectusersid` varchar,
                                                `substatus` varchar,
                                                `targetimage` varchar,
                                                `targetlinkedlogonid` varchar,
                                                `targetlogonid` varchar,
                                                `targetname` varchar,
                                                `targetfilename` varchar,
                                                `targetdomainname` varchar,
                                                `targetparentimage` varchar,
                                                `targetparentprocessid` varchar,
                                                `targetoutbounddomainname` varchar,
                                                `targetoutboundusername` varchar,
                                                `targetprocessaddress` varchar,
                                                `targetprocessguid` varchar,
                                                `targetprocessid` varchar,
                                                `targetservername` varchar,
                                                `targetsid` varchar,
                                                `targetuser` varchar,
                                                `targetusername` varchar,
                                                `targetusersid` varchar,
                                                `taskcontent` varchar,
                                                `taskcontentnew` varchar,
                                                `taskname` varchar,
                                                `templatecontent` varchar,
                                                `terminalsessionid` varchar,
                                                `threat_id` varchar,
                                                `threat_name` varchar,
                                                `ticketencryptiontype` varchar,
                                                `ticketencryptiontypedescription` varchar,
                                                `ticketoptions` varchar,
                                                `ticketoptionsdescription` varchar,
                                                `tokenelevationtype` varchar,
                                                `transactionid` varchar,
                                                `transmittedservices` varchar,
                                                `type` varchar,
                                                `type_id` varchar,
                                                `type_name` varchar,
                                                `user` varchar,
                                                `useraccountcontrol` varchar,
                                                `username` varchar,
                                                `userparameters` varchar,
                                                `userprincipalname` varchar,
                                                `userworkstations` varchar,
                                                `value` varchar,
                                                `verb` varchar,
                                                `version` varchar,
                                                `virtualaccount` varchar,
                                                `wmi_name` varchar,
                                                `wmi_namespace` varchar,
                                                `wmi_filter_path` varchar,
                                                `wmi_operation` varchar,
                                                `workstation` varchar,
                                                `workstationname` varchar,
                                                `process`  varchar)),
                                 `ts` TIMESTAMP(3) METADATA FROM 'timestamp')
WITH (
  'connector' = 'kafka',
  'topic' = 'edr',
  'properties.bootstrap.servers' = '10.0.16.84:9092,10.0.17.13:9092,10.0.36.107:9092,10.0.5.179:9092,10.0.12.164:9092',
  'properties.group.id' = 'flink-edr11',
  'scan.startup.mode' = 'latest-offset',
  'format' = 'json',
 'json.fail-on-missing-field' = 'false',
 'json.ignore-parse-errors' = 'true'
);

 CREATE TABLE default_catalog.default_database.FlinkOut (
  `message` STRING
) WITH (
  'connector' = 'kafka',
  'topic' = 'ams_alert_in',
  'properties.bootstrap.servers' = '10.0.16.84:9092,10.0.17.13:9092,10.0.36.107:9092,10.0.5.179:9092,10.0.12.164:9092',
  'properties.group.id' = 'flink',
  'scan.startup.mode' = 'earliest-offset',
  'format' = 'raw'
);


ADD jar 'flink/flink-1.18.0/bin/jars/flink-sql-connector-kafka-3.0.2-1.18.jar';

EXECUTE STATEMENT SET
BEGIN
SELECT 
  JSON_OBJECT ('event' VALUE JSON_OBJECT('host' VALUE `host`.`name`, 'uuid' VALUE `uuid`, 'created' VALUE `event`.`created`, 'code' VALUE `event`.`code`),
       'observables' VALUE JSON_OBJECT('event' VALUE JSON_OBJECT ('code' VALUE  `event`.`code`, 'type' VALUE  `event`.`type`, 'category' VALUE  `event`.`category`, 'action' VALUE  `event`.`action`, 'channel' VALUE  `event`.`channel`),'host' VALUE JSON_OBJECT ('name' VALUE  `host`.`name`),'user' VALUE JSON_OBJECT ('name' VALUE  `user`.`name`, 'domain' VALUE  `user`.`domain`),'process' VALUE JSON_OBJECT ('name' VALUE  `process`.`name`, 'parent' VALUE  JSON_OBJECT ('name' VALUE  `process`.`parent`.`name`, 'executable' VALUE  `process`.`parent`.`executable`, 'command_line' VALUE  `process`.`parent`.`command_line`), 'executable' VALUE  `process`.`executable`, 'command_line' VALUE  `process`.`command_line`, 'working_directory' VALUE  `process`.`working_directory`, 'pe' VALUE  JSON_OBJECT ('original_file_name' VALUE  `process`.`pe`.`original_file_name`, 'description' VALUE  `process`.`pe`.`description`, 'company' VALUE  `process`.`pe`.`company`, 'product' VALUE  `process`.`pe`.`product`), 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `process`.`hash`.`sha256`, 'imphash' VALUE  `process`.`hash`.`imphash`)),'file' VALUE JSON_OBJECT ('name' VALUE  `file`.`name`, 'path' VALUE  `file`.`path`, 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `file`.`hash`.`sha256`, 'imphash' VALUE  `file`.`hash`.`imphash`)),'registry' VALUE JSON_OBJECT ('path' VALUE  `registry`.`path`, 'value' VALUE  `registry`.`value`),'dns' VALUE JSON_OBJECT ('question' VALUE  JSON_OBJECT ('name' VALUE  `dns`.`question`.`name`)),'source' VALUE JSON_OBJECT ('domain' VALUE  `source`.`domain`, 'ip' VALUE  `source`.`ip`, 'port' VALUE  `source`.`port`),'destination' VALUE JSON_OBJECT ('domain' VALUE  `destination`.`domain`, 'ip' VALUE  `destination`.`ip`, 'port' VALUE  `destination`.`port`),'winlog' VALUE JSON_OBJECT ('targetimage' VALUE  `winlog`.`targetimage`, 'grantedaccess' VALUE  `winlog`.`grantedaccess`, 'eventtype' VALUE  `winlog`.`eventtype`, 'initiated' VALUE  `winlog`.`initiated`, 'user' VALUE  `winlog`.`user`, 'state' VALUE  `winlog`.`state`, 'integritylevel' VALUE  `winlog`.`integritylevel`, 'eventnamespace' VALUE  `winlog`.`eventnamespace`, 'name' VALUE  `winlog`.`name`, 'operation' VALUE  `winlog`.`operation`, 'consumer' VALUE  `winlog`.`consumer`, 'filter' VALUE  `winlog`.`filter`)),
       'observer' value JSON_OBJECT ('type' VALUE `observer`.`type`),
       'organization' VALUE JSON_OBJECT('id' VALUE `organization`.`id`),
       'uuid' VALUE UUID(),
       'alert' VALUE JSON_OBJECT('created' VALUE now(), 'kind' VALUE 'alert', 'level' VALUE 'medium'),
       'rule' VALUE JSON_OBJECT('id' VALUE 'd504ce05-9fc9-4f03-8455-7b24750fd515', 'name' VALUE 'WMI Event Subscription_clone_clone_clone', 'description' VALUE 'Detects creation of WMI event subscription persistence method'),
       'observables_list' VALUE ARRAY['NA'],
       'falsepositives' VALUE ARRAY['Exclude legitimate (vetted) use of WMI event subscription in your network'] ,
       'tacticidlist' VALUE ARRAY['TA0003'],
       'techniqueidlist' VALUE ARRAY['T1546.003']

  , 'source_data' VALUE
  JSON_OBJECT ('event' VALUE JSON_OBJECT('host' VALUE `host`.`name`, 'uuid' VALUE `uuid`, 'created' VALUE `event`.`created`, 'code' VALUE `event`.`code`),
       'observables' VALUE JSON_OBJECT('event' VALUE JSON_OBJECT ('code' VALUE  `event`.`code`, 'type' VALUE  `event`.`type`, 'category' VALUE  `event`.`category`, 'action' VALUE  `event`.`action`, 'channel' VALUE  `event`.`channel`),'host' VALUE JSON_OBJECT ('name' VALUE  `host`.`name`),'user' VALUE JSON_OBJECT ('name' VALUE  `user`.`name`, 'domain' VALUE  `user`.`domain`),'process' VALUE JSON_OBJECT ('name' VALUE  `process`.`name`, 'parent' VALUE  JSON_OBJECT ('name' VALUE  `process`.`parent`.`name`, 'executable' VALUE  `process`.`parent`.`executable`, 'command_line' VALUE  `process`.`parent`.`command_line`), 'executable' VALUE  `process`.`executable`, 'command_line' VALUE  `process`.`command_line`, 'working_directory' VALUE  `process`.`working_directory`, 'pe' VALUE  JSON_OBJECT ('original_file_name' VALUE  `process`.`pe`.`original_file_name`, 'description' VALUE  `process`.`pe`.`description`, 'company' VALUE  `process`.`pe`.`company`, 'product' VALUE  `process`.`pe`.`product`), 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `process`.`hash`.`sha256`, 'imphash' VALUE  `process`.`hash`.`imphash`)),'file' VALUE JSON_OBJECT ('name' VALUE  `file`.`name`, 'path' VALUE  `file`.`path`, 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `file`.`hash`.`sha256`, 'imphash' VALUE  `file`.`hash`.`imphash`)),'registry' VALUE JSON_OBJECT ('path' VALUE  `registry`.`path`, 'value' VALUE  `registry`.`value`),'dns' VALUE JSON_OBJECT ('question' VALUE  JSON_OBJECT ('name' VALUE  `dns`.`question`.`name`)),'source' VALUE JSON_OBJECT ('domain' VALUE  `source`.`domain`, 'ip' VALUE  `source`.`ip`, 'port' VALUE  `source`.`port`),'destination' VALUE JSON_OBJECT ('domain' VALUE  `destination`.`domain`, 'ip' VALUE  `destination`.`ip`, 'port' VALUE  `destination`.`port`),'winlog' VALUE JSON_OBJECT ('targetimage' VALUE  `winlog`.`targetimage`, 'grantedaccess' VALUE  `winlog`.`grantedaccess`, 'eventtype' VALUE  `winlog`.`eventtype`, 'initiated' VALUE  `winlog`.`initiated`, 'user' VALUE  `winlog`.`user`, 'state' VALUE  `winlog`.`state`, 'integritylevel' VALUE  `winlog`.`integritylevel`, 'eventnamespace' VALUE  `winlog`.`eventnamespace`, 'name' VALUE  `winlog`.`name`, 'operation' VALUE  `winlog`.`operation`, 'consumer' VALUE  `winlog`.`consumer`, 'filter' VALUE  `winlog`.`filter`)),
       'observer' value JSON_OBJECT ('type' VALUE `observer`.`type`),
       'organization' VALUE JSON_OBJECT('id' VALUE `organization`.`id`),
       'uuid' VALUE UUID(),
       'alert' VALUE JSON_OBJECT('created' VALUE now(), 'kind' VALUE 'alert', 'level' VALUE 'medium'),
       'rule' VALUE JSON_OBJECT('id' VALUE 'd504ce05-9fc9-4f03-8455-7b24750fd515', 'name' VALUE 'WMI Event Subscription_clone_clone_clone', 'description' VALUE 'Detects creation of WMI event subscription persistence method'),
       'observables_list' VALUE ARRAY['NA'],
       'falsepositives' VALUE ARRAY['Exclude legitimate (vetted) use of WMI event subscription in your network'] ,
       'tacticidlist' VALUE ARRAY['TA0003'],
       'techniqueidlist' VALUE ARRAY['T1546.003']

  )) FROM stream_edr WHERE (`organization`.`id`='3c36bc68') AND ((REGEXP_EXTRACT(cast(`EventID` as VARCHAR), '^19$') is not null OR REGEXP_EXTRACT(cast(`EventID` as VARCHAR), '^20$') is not null OR REGEXP_EXTRACT(cast(`EventID` as VARCHAR), '^21$') is not null) )
SELECT 
  JSON_OBJECT ('event' VALUE JSON_OBJECT('host' VALUE `host`.`name`, 'uuid' VALUE `uuid`, 'created' VALUE `event`.`created`, 'code' VALUE `event`.`code`),
       'observables' VALUE JSON_OBJECT('event' VALUE JSON_OBJECT ('code' VALUE  `event`.`code`, 'type' VALUE  `event`.`type`, 'category' VALUE  `event`.`category`, 'action' VALUE  `event`.`action`, 'channel' VALUE  `event`.`channel`),'host' VALUE JSON_OBJECT ('name' VALUE  `host`.`name`),'user' VALUE JSON_OBJECT ('name' VALUE  `user`.`name`, 'domain' VALUE  `user`.`domain`),'process' VALUE JSON_OBJECT ('name' VALUE  `process`.`name`, 'parent' VALUE  JSON_OBJECT ('name' VALUE  `process`.`parent`.`name`, 'executable' VALUE  `process`.`parent`.`executable`, 'command_line' VALUE  `process`.`parent`.`command_line`), 'executable' VALUE  `process`.`executable`, 'command_line' VALUE  `process`.`command_line`, 'working_directory' VALUE  `process`.`working_directory`, 'pe' VALUE  JSON_OBJECT ('original_file_name' VALUE  `process`.`pe`.`original_file_name`, 'description' VALUE  `process`.`pe`.`description`, 'company' VALUE  `process`.`pe`.`company`, 'product' VALUE  `process`.`pe`.`product`), 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `process`.`hash`.`sha256`, 'imphash' VALUE  `process`.`hash`.`imphash`)),'file' VALUE JSON_OBJECT ('name' VALUE  `file`.`name`, 'path' VALUE  `file`.`path`, 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `file`.`hash`.`sha256`, 'imphash' VALUE  `file`.`hash`.`imphash`)),'registry' VALUE JSON_OBJECT ('path' VALUE  `registry`.`path`, 'value' VALUE  `registry`.`value`),'dns' VALUE JSON_OBJECT ('question' VALUE  JSON_OBJECT ('name' VALUE  `dns`.`question`.`name`)),'source' VALUE JSON_OBJECT ('domain' VALUE  `source`.`domain`, 'ip' VALUE  `source`.`ip`, 'port' VALUE  `source`.`port`),'destination' VALUE JSON_OBJECT ('domain' VALUE  `destination`.`domain`, 'ip' VALUE  `destination`.`ip`, 'port' VALUE  `destination`.`port`),'winlog' VALUE JSON_OBJECT ('targetimage' VALUE  `winlog`.`targetimage`, 'grantedaccess' VALUE  `winlog`.`grantedaccess`, 'eventtype' VALUE  `winlog`.`eventtype`, 'initiated' VALUE  `winlog`.`initiated`, 'user' VALUE  `winlog`.`user`, 'state' VALUE  `winlog`.`state`, 'integritylevel' VALUE  `winlog`.`integritylevel`, 'eventnamespace' VALUE  `winlog`.`eventnamespace`, 'name' VALUE  `winlog`.`name`, 'operation' VALUE  `winlog`.`operation`, 'consumer' VALUE  `winlog`.`consumer`, 'filter' VALUE  `winlog`.`filter`)),
       'observer' value JSON_OBJECT ('type' VALUE `observer`.`type`),
       'organization' VALUE JSON_OBJECT('id' VALUE `organization`.`id`),
       'uuid' VALUE UUID(),
       'alert' VALUE JSON_OBJECT('created' VALUE now(), 'kind' VALUE 'alert', 'level' VALUE 'high'),
       'rule' VALUE JSON_OBJECT('id' VALUE '790c7292-63c3-41c2-a7df-682896ee80af', 'name' VALUE 'Sysmon Blocked File Shredding_clone', 'description' VALUE 'Triggers on any Sysmon "FileBlockShredding" event, which indicates a violation of the configured shredding policy.'),
       'observables_list' VALUE ARRAY['NA'],
       'falsepositives' VALUE ARRAY['Unlikely'] ,
       'tacticidlist' VALUE ARRAY['TA0005'],
       'techniqueidlist' VALUE ARRAY['NA']

  , 'source_data' VALUE
  JSON_OBJECT ('event' VALUE JSON_OBJECT('host' VALUE `host`.`name`, 'uuid' VALUE `uuid`, 'created' VALUE `event`.`created`, 'code' VALUE `event`.`code`),
       'observables' VALUE JSON_OBJECT('event' VALUE JSON_OBJECT ('code' VALUE  `event`.`code`, 'type' VALUE  `event`.`type`, 'category' VALUE  `event`.`category`, 'action' VALUE  `event`.`action`, 'channel' VALUE  `event`.`channel`),'host' VALUE JSON_OBJECT ('name' VALUE  `host`.`name`),'user' VALUE JSON_OBJECT ('name' VALUE  `user`.`name`, 'domain' VALUE  `user`.`domain`),'process' VALUE JSON_OBJECT ('name' VALUE  `process`.`name`, 'parent' VALUE  JSON_OBJECT ('name' VALUE  `process`.`parent`.`name`, 'executable' VALUE  `process`.`parent`.`executable`, 'command_line' VALUE  `process`.`parent`.`command_line`), 'executable' VALUE  `process`.`executable`, 'command_line' VALUE  `process`.`command_line`, 'working_directory' VALUE  `process`.`working_directory`, 'pe' VALUE  JSON_OBJECT ('original_file_name' VALUE  `process`.`pe`.`original_file_name`, 'description' VALUE  `process`.`pe`.`description`, 'company' VALUE  `process`.`pe`.`company`, 'product' VALUE  `process`.`pe`.`product`), 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `process`.`hash`.`sha256`, 'imphash' VALUE  `process`.`hash`.`imphash`)),'file' VALUE JSON_OBJECT ('name' VALUE  `file`.`name`, 'path' VALUE  `file`.`path`, 'hash' VALUE  JSON_OBJECT ('sha256' VALUE  `file`.`hash`.`sha256`, 'imphash' VALUE  `file`.`hash`.`imphash`)),'registry' VALUE JSON_OBJECT ('path' VALUE  `registry`.`path`, 'value' VALUE  `registry`.`value`),'dns' VALUE JSON_OBJECT ('question' VALUE  JSON_OBJECT ('name' VALUE  `dns`.`question`.`name`)),'source' VALUE JSON_OBJECT ('domain' VALUE  `source`.`domain`, 'ip' VALUE  `source`.`ip`, 'port' VALUE  `source`.`port`),'destination' VALUE JSON_OBJECT ('domain' VALUE  `destination`.`domain`, 'ip' VALUE  `destination`.`ip`, 'port' VALUE  `destination`.`port`),'winlog' VALUE JSON_OBJECT ('targetimage' VALUE  `winlog`.`targetimage`, 'grantedaccess' VALUE  `winlog`.`grantedaccess`, 'eventtype' VALUE  `winlog`.`eventtype`, 'initiated' VALUE  `winlog`.`initiated`, 'user' VALUE  `winlog`.`user`, 'state' VALUE  `winlog`.`state`, 'integritylevel' VALUE  `winlog`.`integritylevel`, 'eventnamespace' VALUE  `winlog`.`eventnamespace`, 'name' VALUE  `winlog`.`name`, 'operation' VALUE  `winlog`.`operation`, 'consumer' VALUE  `winlog`.`consumer`, 'filter' VALUE  `winlog`.`filter`)),
       'observer' value JSON_OBJECT ('type' VALUE `observer`.`type`),
       'organization' VALUE JSON_OBJECT('id' VALUE `organization`.`id`),
       'uuid' VALUE UUID(),
       'alert' VALUE JSON_OBJECT('created' VALUE now(), 'kind' VALUE 'alert', 'level' VALUE 'high'),
       'rule' VALUE JSON_OBJECT('id' VALUE '790c7292-63c3-41c2-a7df-682896ee80af', 'name' VALUE 'Sysmon Blocked File Shredding_clone', 'description' VALUE 'Triggers on any Sysmon "FileBlockShredding" event, which indicates a violation of the configured shredding policy.'),
       'observables_list' VALUE ARRAY['NA'],
       'falsepositives' VALUE ARRAY['Unlikely'] ,
       'tacticidlist' VALUE ARRAY['TA0005'],
       'techniqueidlist' VALUE ARRAY['NA']

  )) FROM stream_edr WHERE (`organization`.`id`='3c36bc68') AND ((REGEXP_EXTRACT(cast(`EventID` as VARCHAR), '^28$') is not null) )
END;
