name: Run flink Command on Push

on:
  push:
    branches:
      - main  # You can change this to whatever branch you want to trigger the workflow on

jobs:
  run_xyz_command:
    runs-on: ubuntu-latest  # You can change the operating system if needed
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find SQL files
      id: find_sql_files
      run: |
        sql_files=$(git show --name-only HEAD | grep "\.sql$")
        echo "::set-output name=sql_files::$sql_files"
    
    - name: SSH into remote instance and run command
      uses: appleboy/ssh-action@v0.3.1
      with:
        host: ec2-18-207-123-14.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Retrieve SQL files from output
            sql_files="${{ steps.find_sql_files.outputs.sql_files }}"

            if [ -n "$sql_files" ]; then
              # Ensure Flink installation path is correct
              FLINK_HOME=/home/ec2-user/flink/flink-1.18.0
              # Loop through files and execute Flink command
              for file in $sql_files; do
                $FLINK_HOME/bin/sql-client.sh -f "$file" -e 10.0.6.133:8081
              done
            fi
