name: Run flink Command on Push

on:
  push:
    branches:
      - main  # You can change this to whatever branch you want to trigger the workflow on

jobs:
  run_xyz_command:
    runs-on: ubuntu-latest  # You can change the operating system if needed
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find SQL files
      id: find_sql_files
      run: |
        latest_commit=$(git rev-parse HEAD)
        prev_commit=$(git rev-parse HEAD^ 2>/dev/null || echo "")
        if [ -z "$prev_commit" ]; then
          prev_commit=$(git hash-object -t tree /dev/null)
        fi
        sql_files=$(git diff --name-only $prev_commit $latest_commit | grep ".sql")
        echo "::set-output name=sql_files::$(echo "$sql_files")"
    
    - name: SSH into remote instance and run command
      run: |
        ssh -i "clickhouse.pem" ec2-user@ec2-18-207-123-14.compute-1.amazonaws.com << 'EOF'
        sql_files="${{ steps.find_sql_files.outputs.sql_files }}"
        if [ -n "$sql_files" ]; then
          for file in $sql_files; do
            sudo flink/flink-1.18.0/bin/sql-client.sh -f "$file" -e 10.0.6.133:8081
          done
        fi

